/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // 手动定义的侧边栏结构，确保逻辑顺序清晰
  tutorialSidebar: [
    'welcome',
    {
      type: 'category',
      label: '📖 产品概览 (Introduction)',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: 'FZS 产品概览',
        description: '了解 FZS 的架构、特性及应用场景',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'intro',
        },
      ],
    },
    {
      type: 'category',
      label: '⚡ 快速上手 (Quick Start)',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'quick-start',
        },
      ],
    },
    {
      type: 'html',
      value: '<span style="color:var(--ifm-color-primary); font-weight:bold; margin-top:20px; display:block;">操作指南</span>',
    },
    {
      type: 'category',
      label: '🖥️ FZS Web 用户手册',
      collapsible: true,
      link: {
        type: 'doc',
        id: 'fzs-web/index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'fzs-web',
        },
      ],
    },
    {
      type: 'category',
      label: '⚙️ FZS Web Server 开发手册',
      collapsible: true,
      link: {
        type: 'doc',
        id: 'fzs-web-server/index'
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'fzs-web-server',
        },
      ],
    },
    {
      type: 'html',
      value: '<div style="height:1px; background:var(--ifm-color-emphasis-200); margin: 10px 0;"></div>',
    },
    'changelog',
  ],
};

module.exports = sidebars;
